# SESSION 8 - Data Cleaning (Part 3: Duplicates, Typos, Consistency)

**Curriculum Module:** Data Collection, Cleaning, Visualization and Analysis  
**Session:** 08 - Data Cleaning (Part 3: Duplicates, Typos, Consistency)  
**Status:** ✅ Completed

---

## 📋 Topics Covered
1. **Detecting Duplicates**: Using `.duplicated()` with `subset` and `keep` parameters, and identifying frequency distributions using `.value_counts()`.
2. **Removing Duplicates**: Eliminating redundant rows via `.drop_duplicates()` to maintain dataset integrity.
3. **Fixing Typos in Categorical Data**: Standardizing spelling and naming variations using `.replace()` with dictionary mappings.
4. **String Normalization**: Trimming extraneous whitespace with `.str.strip()` and standardizing casing with `.str.lower()`.
5. **Unifying Category Formats**: Mapping heterogeneous user inputs (e.g. `'Yes'`, `'y'`, `'No'`, `'N'`) into binary indicator flags (`1` / `0`).

---

## Task 1: Find Duplicate Zomato Orders with `duplicated()`

**Problem Statement:**  
*Download a small sample of your recent Zomato order history as a CSV (or create a mock CSV with restaurant names and order dates), then use pandas' `duplicated()` function to find and print any duplicate orders based on restaurant name and date.*

In [1]:
import pandas as pd

# Load Zomato order history dataset
df_zomato = pd.read_csv('zomato_order_history.csv')
print('Zomato Orders Dataset Preview:')
print(df_zomato.head(5))

# Identify duplicate orders based on restaurant name and order date
# Using keep=False marks all occurrences of duplicates for complete audit
duplicate_mask_all = df_zomato.duplicated(subset=['restaurant_name', 'order_date'], keep=False)
duplicate_orders_all = df_zomato[duplicate_mask_all].sort_values(by=['restaurant_name', 'order_date'])

print(f'\nTotal orders flagged in duplicate clusters: {len(duplicate_orders_all)}')
print('\nAll duplicate order occurrences (matching restaurant & date):')
print(duplicate_orders_all)

# Using keep='first' marks only the redundant duplicate rows (excluding original)
duplicate_mask_subsequent = df_zomato.duplicated(subset=['restaurant_name', 'order_date'], keep='first')
duplicate_orders_subsequent = df_zomato[duplicate_mask_subsequent]

print(f'\nNumber of redundant rows to drop: {len(duplicate_orders_subsequent)}')
print('Redundant rows:')
duplicate_orders_subsequent

Zomato Orders Dataset Preview:
  order_id restaurant_name  order_date  amount   cuisine
0     Z101        Truffles  2026-10-15   450.0   Burgers
1     Z102   Meghana Foods  2026-10-16   620.0   Biryani
2     Z103        Truffles  2026-10-15   450.0   Burgers
3     Z104    Corner House  2026-10-17   280.0  Desserts
4     Z105        Bawarchi  2026-10-18   550.0   Biryani

Total orders flagged in duplicate clusters: 6

All duplicate order occurrences (matching restaurant & date):
  order_id restaurant_name  order_date  amount  cuisine
4     Z105        Bawarchi  2026-10-18   550.0  Biryani
7     Z108        Bawarchi  2026-10-18   550.0  Biryani
1     Z102   Meghana Foods  2026-10-16   620.0  Biryani
5     Z106   Meghana Foods  2026-10-16   320.0  Biryani
0     Z101        Truffles  2026-10-15   450.0  Burgers
2     Z103        Truffles  2026-10-15   450.0  Burgers

Number of redundant rows to drop: 3
Redundant rows:
  order_id restaurant_name  order_date  amount  cuisine
2     Z103        Truffles  2026-10-15   450.0  Burgers
5     Z106   Meghana Foods  2026-10-16   320.0  Biryani
7     Z108        Bawarchi  2026-10-18   550.0  Biryani

  order_id restaurant_name  order_date  amount  cuisine
2     Z103        Truffles  2026-10-15   450.0  Burgers
5     Z106   Meghana Foods  2026-10-16   320.0  Biryani
7     Z108        Bawarchi  2026-10-18   550.0  Biryani

---

## Task 2: Identify Repeated Reviews with `value_counts()`

**Problem Statement:**  
*Given a list of Flipkart product reviews with some duplicate entries, use `value_counts()` in pandas to identify which review texts are repeated most often and display the top 3 most common duplicate reviews.*

In [2]:
# Load Flipkart product reviews dataset
df_reviews = pd.read_csv('flipkart_reviews.csv')

print(f'Total reviews in dataset: {len(df_reviews)}')

# Count frequency of each unique review text
review_counts = df_reviews['review_text'].value_counts()

# Extract top 3 most frequently occurring duplicate reviews
top_3_duplicate_reviews = review_counts.head(3)

print('Top 3 Most Common Duplicate Reviews:')
for rank, (text, count) in enumerate(top_3_duplicate_reviews.items(), 1):
    print(f'{rank}. "{text}" -> Repeated {count} times')

print('\nDetailed Series Output:')
top_3_duplicate_reviews

Total reviews in dataset: 15
Top 3 Most Common Duplicate Reviews:
1. "4" -> Repeated 5 times
2. " highly recommend!" -> Repeated 4 times
3. " do not buy!" -> Repeated 3 times

Detailed Series Output:
review_text
4                     5
 highly recommend!    4
 do not buy!          3

---

## Task 3: Exact Duplicate Removal with `drop_duplicates()`

**Problem Statement:**  
*Create a DataFrame with mock data for Spotify playlists, including playlist names and creator usernames, where some rows are exact duplicates. Use `drop_duplicates()` to remove duplicate playlists and print the cleaned DataFrame.*

In [3]:
# Load Spotify playlists dataset with exact duplicate rows
df_spotify = pd.read_csv('spotify_playlists.csv')

print(f'Initial DataFrame Shape: {df_spotify.shape}')
print('Initial Dataset (with exact duplicate rows):')
print(df_spotify)

# Remove exact duplicate rows and reset index
df_spotify_cleaned = df_spotify.drop_duplicates().reset_index(drop=True)

print(f'\nCleaned DataFrame Shape: {df_spotify_cleaned.shape}')
print(f'Duplicates removed: {df_spotify.shape[0] - df_spotify_cleaned.shape[0]} rows')

print('\nCleaned Spotify Playlists DataFrame:')
df_spotify_cleaned

Initial DataFrame Shape: (10, 4)
Initial Dataset (with exact duplicate rows):
      playlist_name creator_username      genre  tracks_count
0       Lo-Fi Beats         kathan_g      Lo-Fi            45
1    Workout Energy           arav_m    Fitness            60
2   Bollywood Retro          priya_s  Bollywood            80
3       Lo-Fi Beats         kathan_g      Lo-Fi            45
4  Late Night Chill          rohit_k    Ambient            35
5    Workout Energy           arav_m    Fitness            60
6     Rock Classics         vikram_r       Rock            95
7     Pop Hits 2026          sneha_p        Pop            50
8       Lo-Fi Beats         kathan_g      Lo-Fi            45
9  Acoustic Morning         ananya_d   Acoustic            40

Cleaned DataFrame Shape: (7, 4)
Duplicates removed: 3 rows

Cleaned Spotify Playlists DataFrame:
      playlist_name creator_username      genre  tracks_count
0       Lo-Fi Beats         kathan_g      Lo-Fi            45
1    Workout Energy           arav_m    Fitness            60
2   Bollywood Retro          priya_s  Bollywood            80
3  Late Night Chill          rohit_k    Ambient            35
4     Rock Classics         vikram_r       Rock            95
5     Pop Hits 2026          sneha_p        Pop            50
6  Acoustic Morning         ananya_d   Acoustic            40

      playlist_name creator_username      genre  tracks_count
0       Lo-Fi Beats         kathan_g      Lo-Fi            45
1    Workout Energy           arav_m    Fitness            60
2   Bollywood Retro          priya_s  Bollywood            80
3  Late Night Chill          rohit_k    Ambient            35
4     Rock Classics         vikram_r       Rock            95
5     Pop Hits 2026          sneha_p        Pop            50
6  Acoustic Morning         ananya_d   Acoustic            40

---

## Task 4: Standardize Typos in Categorical Data with `replace()`

**Problem Statement:**  
*Suppose you have a DataFrame of Instagram usernames where some entries have typos (like `'insta_queen'`, `'insta queen'`, `'instaqueen'`). Use the `replace()` function to standardize all these variants to `'instaqueen'`.*

In [4]:
# Load Instagram users dataset with username variants
df_insta = pd.read_csv('instagram_users.csv')

print('Original Instagram Usernames:')
print(df_insta[['user_id', 'username']])

# Define dictionary mapping typo variants to the canonical username
typo_mapping = {
    'insta_queen': 'instaqueen',
    'insta queen': 'instaqueen'
}

# Standardize username variants
df_insta['username_clean'] = df_insta['username'].replace(typo_mapping)

print('\nStandardized Instagram Usernames:')
comparison = df_insta[['user_id', 'username', 'username_clean', 'followers_count']]
print(comparison)

print('\nUnique counts before vs after cleaning:')
print(f'Before: {df_insta["username"].nunique()} unique usernames')
print(f'After:  {df_insta["username_clean"].nunique()} unique usernames')

Original Instagram Usernames:
   user_id       username
0      101    insta_queen
1      102     travel_bug
2      103    insta queen
3      104      tech_geek
4      105     instaqueen
5      106    foodie_life
6      107    insta_queen
7      108  fitness_freak
8      109    insta queen
9      110      coder_hub

Standardized Instagram Usernames:
   user_id       username username_standardized  followers_count
0      101    insta_queen            instaqueen            45200
1      102     travel_bug            travel_bug            12500
2      103    insta queen            instaqueen            45200
3      104      tech_geek             tech_geek             8900
4      105     instaqueen            instaqueen            45200
5      106    foodie_life           foodie_life            34000
6      107    insta_queen            instaqueen            45200
7      108  fitness_freak         fitness_freak            62000
8      109    insta queen            instaqueen            45200
9      110      coder_hub             coder_hub            19000

Unique counts before vs after cleaning:
Before: 8 unique usernames
After:  6 unique usernames

   user_id       username username_standardized  followers_count
0      101    insta_queen            instaqueen            45200
1      102     travel_bug            travel_bug            12500
2      103    insta queen            instaqueen            45200
3      104      tech_geek             tech_geek             8900
4      105     instaqueen            instaqueen            45200
5      106    foodie_life           foodie_life            34000
6      107    insta_queen            instaqueen            45200
7      108  fitness_freak         fitness_freak            62000
8      109    insta queen            instaqueen            45200
9      110      coder_hub             coder_hub            19000

---

## Task 5: Normalize Inconsistent Payment Status to Binary Flags

**Problem Statement:**  
*You have a DataFrame column for payment status from a Paytm-like app with mixed values: `'Yes'`, `'yes'`, `'Y'`, `'No'`, `'no'`, `'N'`, and some with extra spaces. Write code to unify this column so all paid statuses become 1 and all unpaid statuses become 0, trimming whitespace and fixing capitalization where needed.*  
*Hint: Use `str.strip()`, `str.lower()`, and map/replace methods in pandas.*

In [5]:
# Load Paytm payment status dataset
df_paytm = pd.read_csv('paytm_payment_status.csv')

print('Original Raw Payment Status Column (with spaces & mixed cases):')
for val in df_paytm['payment_status']:
    print(f'Raw representation: {repr(val)}')

# Step 1: Strip leading/trailing whitespaces and convert to lowercase
cleaned_status = df_paytm['payment_status'].str.strip().str.lower()

# Step 2: Define mapping to binary indicator flags (1 = Paid, 0 = Unpaid)
status_binary_map = {
    'yes': 1,
    'y': 1,
    'no': 0,
    'n': 0
}

# Step 3: Map cleaned strings to integer binary flags
df_paytm['is_paid'] = cleaned_status.map(status_binary_map)

print('\nUnified Payment Status Table:')
result_table = df_paytm[['txn_id', 'customer_id', 'payment_status', 'is_paid']]
print(result_table)
print(f'\nTarget column data type: {df_paytm["is_paid"].dtype}')

Original Raw Payment Status Column (with spaces & mixed cases):
Raw representation: 'Yes'
Raw representation: ' yes '
Raw representation: 'Y'
Raw representation: 'No'
Raw representation: ' no '
Raw representation: 'N'
Raw representation: ' YES '
Raw representation: ' y '
Raw representation: ' NO '
Raw representation: 'n'

Unified Payment Status Table:
   txn_id customer_id payment_status  is_paid
0  TXN801        C101            Yes        1
1  TXN802        C102           yes         1
2  TXN803        C103              Y        1
3  TXN804        C104             No        0
4  TXN805        C105            no         0
5  TXN806        C106              N        0
6  TXN807        C107           YES         1
7  TXN808        C108             y         1
8  TXN809        C109            NO         0
9  TXN810        C110              n        0

Target column data type: int64

   txn_id customer_id payment_status  is_paid
0  TXN801        C101            Yes        1
1  TXN802        C102           yes         1
2  TXN803        C103              Y        1
3  TXN804        C104             No        0
4  TXN805        C105            no         0
5  TXN806        C106              N        0
6  TXN807        C107           YES         1
7  TXN808        C108             y         1
8  TXN809        C109            NO         0
9  TXN810        C110              n        0

---

## 🎯 Key Takeaways & Best Practices
- **Duplication Diagnostics**: Use `duplicated(keep=False)` to inspect entire duplicate clusters before dropping; use `duplicated(keep='first')` to single out redundant occurrences.
- **Frequency Auditing**: `.value_counts()` serves as an essential preliminary check to catch spam bots, repeated reviews, or duplicate default entries.
- **Idempotent De-duplication**: `drop_duplicates()` eliminates exact row matches cleanly. When keys dictate uniqueness (e.g. `order_id` or `user_id`), specify `subset=['key_column']`.
- **Systematic Typo Remediation**: When handling small controlled vocabularies, `.replace(dict_mapping)` provides deterministic, safe corrections. For large-scale fuzzy typos, consider phonetic algorithms or Levenshtein distance libraries (`thefuzz`).
- **Data Hygiene Pipeline**: String data requires standard sequential hygiene: `.str.strip()` $\rightarrow$ `.str.lower()` $\rightarrow$ `.map(binary_dict)` to avoid silent parsing mismatches.