# SESSION 5 - Data Collection using Pandas (Part 2)

**Curriculum Module:** Data Collection, Cleaning, Visualization and Analysis  
**Session:** 05 - Data Collection using Pandas (Part 2)  
**Status:** ✅ Completed

---

## 📋 Topics Covered
1. **Reading data from Relational Databases (MySQL / PostgreSQL / SQLite)** using `pd.read_sql()` & `pd.read_sql_query()` via SQLAlchemy.
2. **Web-based extraction (Intro only)**: Fetching data from REST API endpoints and JSON URLs directly into DataFrames via `pd.read_json()`.
3. **Modern File Path Handling**: Using Python's standard `pathlib.Path` for cross-platform, robust file references.
4. **Merging Datasets**: Performing relational database joins (inner/outer) on shared keys using `pd.merge()`.
5. **Concatenation Concepts**: Appending datasets along rows using `pd.concat()` and resetting indices.

---

### Environment Setup
Ensure `pandas`, `sqlalchemy`, and database drivers (such as `psycopg2` or `pymysql`) are installed.

### 🛠️ Database Setup (SQLAlchemy Engine)
In enterprise backends (like Zomato or BookMyShow), relational databases like MySQL or PostgreSQL are used.

```python
# PostgreSQL connection URI format:
# engine = create_engine('postgresql+psycopg2://<user>:<password>@<host>:<port>/<dbname>')

# MySQL connection URI format:
# engine = create_engine('mysql+pymysql://<user>:<password>@<host>:<port>/<dbname>')
```

To make this notebook self-contained and immediately runnable on any machine without requiring a live external DB server, we will demonstrate using SQLite with the exact same SQLAlchemy engine API.

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from pathlib import Path

# Initialize database engine using SQLAlchemy
# (Note: In production MySQL use 'mysql+pymysql://root:password@localhost:3306/zomato')
# (In production PostgreSQL use 'postgresql+psycopg2://postgres:password@localhost:5432/movies_db')
engine = create_engine('sqlite:///session5_local.db')

# Seed sample 'restaurants' and 'movies' tables for demonstration
df_restaurants_seed = pd.read_csv('restaurants.csv')
df_restaurants_seed.to_sql('restaurants', con=engine, if_exists='replace', index=False)

df_movies_seed = pd.read_csv('movies.csv')
df_movies_seed.to_sql('movies', con=engine, if_exists='replace', index=False)

print('Database connected and tables initialized successfully!')

Database connected and tables initialized successfully!

---

## Task 1: Connect to Database & Load Table with `pd.read_sql()`

**Problem Statement:**  
*Connect to a MySQL or PostgreSQL database using SQLAlchemy and pandas, then use `pd.read_sql()` to load the entire `restaurants` table (imagine Zomato backend) into a DataFrame and display the first 5 rows.*

In [2]:
# Connect and load the entire 'restaurants' table
# pd.read_sql accepts the table name directly when passing a connection engine
df_restaurants = pd.read_sql('restaurants', con=engine)

# Display the first 5 rows
print('First 5 rows of Zomato restaurants table:')
df_restaurants.head(5)

First 5 rows of Zomato restaurants table:
   restaurant_id       name       cuisine  rating       city  cost_for_two
0            101   Truffles      American     4.5  Bangalore           800
1            102   Bawarchi       Biryani     4.2  Hyderabad           600
2            103  Peter Cat   Continental     4.4    Kolkata          1200
3            104   Bademiya       Mughlai     4.1     Mumbai           700
4            105    Karim's  North Indian     4.3      Delhi           900

   restaurant_id       name       cuisine  rating       city  cost_for_two
0            101   Truffles      American     4.5  Bangalore           800
1            102   Bawarchi       Biryani     4.2  Hyderabad           600
2            103  Peter Cat   Continental     4.4    Kolkata          1200
3            104   Bademiya       Mughlai     4.1     Mumbai           700
4            105    Karim's  North Indian     4.3      Delhi           900

---

## Task 2: Filtered Data Retrieval with `pd.read_sql_query()`

**Problem Statement:**  
*Use `pd.read_sql_query()` to fetch only the `name` and `rating` columns from a `movies` table (think BookMyShow-like data) where rating is above 8, and print the resulting DataFrame.*  
*Hint: Write a custom SQL SELECT query as the first argument to `pd.read_sql_query()`.*

In [3]:
# Custom SQL query selecting only 'name' and 'rating' where rating > 8
query = '''
SELECT name, rating 
FROM movies 
WHERE rating > 8;
'''

# Execute query using pd.read_sql_query()
df_top_movies = pd.read_sql_query(query, con=engine)

print('BookMyShow Top Rated Movies (Rating > 8):')
df_top_movies

BookMyShow Top Rated Movies (Rating > 8):
                name  rating
0          Inception     8.8
1       Interstellar     8.7
2    The Dark Knight     9.0
3        Oppenheimer     8.9
4  Avengers: Endgame     8.4
5         Fight Club     8.8

                name  rating
0          Inception     8.8
1       Interstellar     8.7
2    The Dark Knight     9.0
3        Oppenheimer     8.9
4  Avengers: Endgame     8.4
5         Fight Club     8.8

---

## Task 3: Ingest JSON Dataset Directly from REST API URL

**Problem Statement:**  
*Read a JSON dataset from the URL `https://jsonplaceholder.typicode.com/users` using pandas, convert it into a DataFrame, and print the usernames column.*  
*Hint: Use `pd.read_json()` directly with the URL.*

In [4]:
# REST API endpoint
url = 'https://jsonplaceholder.typicode.com/users'

# Read JSON directly from URL into DataFrame
df_users_api = pd.read_json(url)

# Display the 'username' column
print('Usernames extracted from JSON API endpoint:')
print(df_users_api['username'])

Usernames extracted from JSON API endpoint:
0                Bret
1           Antonette
2            Samantha
3            Karianne
4              Kamren
5    Leopoldo_Corkery
6        Elwyn.Skiles
7       Maxime_Nienow
8            Delphine
9      Moriah.Stanton

---

## Task 4: File Path Handling with `pathlib` & Merging Datasets

**Problem Statement:**  
*You have two CSV files: `orders.csv` (`order_id`, `user_id`, `amount`) and `users.csv` (`user_id`, `username`). Load both into DataFrames using `pathlib` for file paths, then merge them on `user_id` to show a combined table with `username` and `amount`.*

In [5]:
from pathlib import Path

# Define robust file paths using pathlib.Path
base_path = Path.cwd()
orders_file = base_path / 'orders.csv'
users_file = base_path / 'users.csv'

# Load both CSV files into DataFrames
df_orders = pd.read_csv(orders_file)
df_users = pd.read_csv(users_file)

# Merge DataFrames on 'user_id'
df_merged = pd.merge(df_orders, df_users, on='user_id', how='inner')

# Select only 'username' and 'amount'
result_table = df_merged[['username', 'amount']]

print('Combined Table (Username & Order Amount):')
result_table

Combined Table (Username & Order Amount):
      username   amount
0     john_doe   250.50
1      alice_w   149.00
2     john_doe   899.00
3    bob_smith   450.00
4  emma_watson  1200.75
5      alice_w   320.00
6    charlie_b    99.00
7     kathan_g   750.25

      username   amount
0     john_doe   250.50
1      alice_w   149.00
2     john_doe   899.00
3    bob_smith   450.00
4  emma_watson  1200.75
5      alice_w   320.00
6    charlie_b    99.00
7     kathan_g   750.25

---

## Task 5: Concatenating Datasets with `pd.concat()` & Index Reset

**Problem Statement:**  
*Concatenate two DataFrames representing `today_orders` and `yesterday_orders` (each with columns: `order_id`, `item`, `price`), and display the combined DataFrame.*  
*Constraint: Use `pd.concat()` and reset the index after concatenation.*

In [6]:
# Create sample DataFrames for today's and yesterday's orders
today_orders = pd.DataFrame({
    'order_id': [101, 102],
    'item': ['Burger', 'Pizza'],
    'price': [150, 350]
})

yesterday_orders = pd.DataFrame({
    'order_id': [99, 100],
    'item': ['Pasta', 'Sandwich'],
    'price': [250, 120]
})

# Concatenate along rows (axis=0) and reset index
# Using ignore_index=True resets the index cleanly in one operation
combined_orders = pd.concat([yesterday_orders, today_orders], ignore_index=True)

print('Combined Orders (Yesterday + Today with reset index):')
combined_orders

Combined Orders (Yesterday + Today with reset index):
   order_id      item  price
0        99     Pasta    250
1       100  Sandwich    120
2       101    Burger    150
3       102     Pizza    350

   order_id      item  price
0        99     Pasta    250
1       100  Sandwich    120
2       101    Burger    150
3       102     Pizza    350

---

## 🎯 Key Takeaways & Best Practices
- **SQLAlchemy & Pandas Integration**: `pd.read_sql()` simplifies pulling whole tables, while `pd.read_sql_query()` pushes filtering to the SQL database engine, minimizing memory usage.
- **REST API Ingestion**: `pd.read_json()` handles HTTP/HTTPS URLs directly, parsing JSON array responses into structured tabular format automatically.
- **Pathlib vs String Paths**: `pathlib.Path` ensures code runs reliably across Windows (backslashes) and Linux/macOS (forward slashes) without path delimiter errors.
- **pd.merge() vs pd.concat()**:
  - `pd.merge()` performs key-based relational joins (like SQL `JOIN`).
  - `pd.concat()` stacks DataFrames vertically or horizontally (like SQL `UNION ALL`). Always remember `ignore_index=True` to prevent duplicate index labels.