# SESSION 9 - Working with Date & Time Data

**Curriculum Module:** Data Collection, Cleaning, Visualization and Analysis  
**Session:** 09 - Working with Date & Time Data  
**Status:** ✅ Completed

---

## 📋 Topics Covered
1. **Converting Strings to Datetime**: Utilizing `pd.to_datetime()` with explicit datetime format specifiers.
2. **Extracting Datetime Components**: Leveraging the `.dt` accessor to extract `year`, `month`, `day`, `weekday` (`day_name()`), and `quarter`.
3. **Datetime Indexing & Time-Series Resampling**: Setting datetime indices and calculating aggregations over time frequencies (`df.resample('W').size()`).
4. **Timezone Handling & Localization**: Converting UTC timestamps to regional timezones (`Asia/Kolkata` IST: UTC + 5:30) via `.tz_localize()` and `.tz_convert()`.
5. **Feature Engineering with Temporal Data**: Generating domain features such as `is_weekend` using boolean indexing and numpy integration.

---

## Task 1: Convert String Delivery Timestamps to Datetime

**Problem Statement:**  
*Given a list of delivery timestamps as strings (e.g., `['2024-06-01 14:30', '2024-06-02 09:15', '2024-06-03 20:45']`), use pandas and `pd.to_datetime()` to convert them into datetime objects and print the result.*

In [1]:
import pandas as pd
import numpy as np

# Input list of string delivery timestamps
delivery_timestamps = ['2024-06-01 14:30', '2024-06-02 09:15', '2024-06-03 20:45']

# Convert string list to pandas DatetimeIndex
datetime_objects = pd.to_datetime(delivery_timestamps)

print('Converted Datetime Objects:')
print(datetime_objects)
print(f'\nResult Dtype: {datetime_objects.dtype}')
print(f'Underlying object type: {type(datetime_objects)}')

Converted Datetime Objects:
DatetimeIndex(['2024-06-01 14:30:00', '2024-06-02 09:15:00',
               '2024-06-03 20:45:00'],
              dtype='datetime64[ns]', freq=None)

Result Dtype: datetime64[ns]
Underlying object type: <class 'pandas.core.indexes.datetimes.DatetimeIndex'>

---

## Task 2: Extract Year, Month, and Weekday from Order Dates

**Problem Statement:**  
*Load a CSV file containing order dates from a Flipkart-style order history (column: `'order_date'`, format: `'YYYY-MM-DD HH:MM:SS'`). Extract the year, month, and weekday for each order and add them as new columns in the DataFrame.*

In [2]:
# Load Flipkart order history dataset
df_flipkart = pd.read_csv('flipkart_orders.csv')

# Convert 'order_date' column to datetime type
df_flipkart['order_date'] = pd.to_datetime(df_flipkart['order_date'], format='%Y-%m-%d %H:%M:%S')

# Extract datetime components using the .dt accessor
df_flipkart['year'] = df_flipkart['order_date'].dt.year
df_flipkart['month'] = df_flipkart['order_date'].dt.month
df_flipkart['weekday'] = df_flipkart['order_date'].dt.day_name()

print('Flipkart Orders with Extracted Temporal Components (First 5 Rows):')
preview = df_flipkart[['order_id', 'customer_id', 'order_date', 'year', 'month', 'weekday', 'amount']]
preview.head(5)

Flipkart Orders with Extracted Temporal Components (First 5 Rows):
  order_id customer_id          order_date  year  month   weekday  amount
0   OD1001        C101 2024-06-01 10:15:30  2024      6  Saturday  1299.0
1   OD1002        C102 2024-06-02 14:22:15  2024      6    Sunday   649.0
2   OD1003        C103 2024-06-04 18:45:00  2024      6   Tuesday  1499.0
3   OD1004        C104 2024-06-07 09:30:45  2024      6    Friday   499.0
4   OD1005        C105 2024-06-08 20:10:00  2024      6  Saturday  1199.0

  order_id          order_date  year  month   weekday
0   OD1001 2024-06-01 10:15:30  2024      6  Saturday
1   OD1002 2024-06-02 14:22:15  2024      6    Sunday
2   OD1003 2024-06-04 18:45:00  2024      6   Tuesday
3   OD1004 2024-06-07 09:30:45  2024      6    Friday
4   OD1005 2024-06-08 20:10:00  2024      6  Saturday

---

## Task 3: Datetime Indexing & Weekly Order Resampling

**Problem Statement:**  
*Set the `'order_date'` column as the index of your DataFrame and use resampling to calculate the total number of orders placed each week.*  
*Hint: Use `df.resample('W').size()` after setting the datetime index.*

In [3]:
# Set 'order_date' as the DataFrame index
df_indexed = df_flipkart.set_index('order_date')

# Resample data on a weekly basis ('W') and compute order counts
weekly_order_counts = df_indexed.resample('W').size()

print('Weekly Total Orders Placed (Resampled):')
print(weekly_order_counts)

print(f'\nTotal orders aggregated across all weeks: {weekly_order_counts.sum()}')

Weekly Total Orders Placed (Resampled):
order_date
2024-06-02    2
2024-06-09    4
2024-06-16    3
2024-06-23    4
2024-06-30    3
Freq: W-SUN

Total orders aggregated across all weeks: 16

---

## Task 4: Timezone Localization & Conversion (UTC to Asia/Kolkata)

**Problem Statement:**  
*Suppose you have a DataFrame of Instagram posts with a `'posted_at'` column in UTC. Convert these timestamps to `'Asia/Kolkata'` timezone and display the first 5 converted times.*

In [4]:
# Load Instagram posts dataset
df_insta = pd.read_csv('instagram_posts.csv')

# Step 1: Parse to datetime and localize as UTC timezone-aware
df_insta['posted_at_utc'] = pd.to_datetime(df_insta['posted_at']).dt.tz_localize('UTC')

# Step 2: Convert timezone from UTC to 'Asia/Kolkata' (IST = UTC + 5:30)
df_insta['posted_at_ist'] = df_insta['posted_at_utc'].dt.tz_convert('Asia/Kolkata')

print('Instagram Posts - UTC vs IST Timezone Comparison (First 5):')
tz_comparison = df_insta[['post_id', 'username', 'posted_at_utc', 'posted_at_ist']]
tz_comparison.head(5)

Instagram Posts - UTC vs IST Timezone Comparison (First 5):
  post_id  username             posted_at_utc             posted_at_ist
0   IG801  kathan_g 2024-06-01 12:30:00+00:00 2024-06-01 18:00:00+05:30
1   IG802    arav_m 2024-06-02 03:15:00+00:00 2024-06-02 08:45:00+05:30
2   IG803   priya_s 2024-06-03 14:45:00+00:00 2024-06-03 20:15:00+05:30
3   IG804   rohit_k 2024-06-05 08:20:00+00:00 2024-06-05 13:50:00+05:30
4   IG805  ananya_d 2024-06-07 20:10:00+00:00 2024-06-08 01:40:00+05:30

  post_id  username             posted_at_utc             posted_at_ist
0   IG801  kathan_g 2024-06-01 12:30:00+00:00 2024-06-01 18:00:00+05:30
1   IG802    arav_m 2024-06-02 03:15:00+00:00 2024-06-02 08:45:00+05:30
2   IG803   priya_s 2024-06-03 14:45:00+00:00 2024-06-03 20:15:00+05:30
3   IG804   rohit_k 2024-06-05 08:20:00+00:00 2024-06-05 13:50:00+05:30
4   IG805  ananya_d 2024-06-07 20:10:00+00:00 2024-06-08 01:40:00+05:30

---

## Task 5: Feature Engineering - `is_weekend` Flag

**Problem Statement:**  
*Create a new feature called `'is_weekend'` in your DataFrame that marks `True` if an order was placed on Saturday or Sunday, and `False` otherwise.*  
*Constraint: Do not use any external libraries except pandas and numpy.*

In [5]:
# In pandas, dt.dayofweek represents: Monday=0, Tuesday=1, ..., Saturday=5, Sunday=6
# Check if the day of week is in [5, 6] (Saturday or Sunday)
df_flipkart['is_weekend'] = df_flipkart['order_date'].dt.dayofweek.isin([5, 6])

# Display sample orders showing weekday name and corresponding is_weekend flag
print('Flipkart Orders with engineered is_weekend feature (Sample View):')
weekend_view = df_flipkart[['order_id', 'order_date', 'weekday', 'is_weekend', 'item_name']]
print(weekend_view.head(8))

# Breakdown of orders placed on Weekend vs Weekdays
print('\nOrder Count by Weekend vs Weekday:')
print(df_flipkart['is_weekend'].value_counts().rename({True: 'Weekend', False: 'Weekday'}))

Flipkart Orders with engineered is_weekend feature (Sample View):
  order_id          order_date    weekday  is_weekend               item_name
0   OD1001 2024-06-01 10:15:30   Saturday        True        boAt Rockerz 450
1   OD1002 2024-06-02 14:22:15     Sunday        True  SanDisk 128GB Pendrive
2   OD1003 2024-06-04 18:45:00    Tuesday       False     Fastrack Smartwatch
3   OD1004 2024-06-07 09:30:45     Friday       False       HP Wireless Mouse
4   OD1005 2024-06-08 20:10:00   Saturday        True           Noise Earbuds
5   OD1006 2024-06-09 11:05:20     Sunday        True         Sony WH-1000XM5
6   OD1007 2024-06-12 16:40:10  Wednesday       False   Samsung Galaxy Tab S9
7   OD1008 2024-06-15 13:15:00   Saturday        True        Dell Inspiron 15

Order Count by Weekend vs Weekday:
is_weekend
Weekend    10
Weekday     6
Name: count, dtype: int64

  order_id          order_date    weekday  is_weekend
0   OD1001 2024-06-01 10:15:30   Saturday        True
1   OD1002 2024-06-02 14:22:15     Sunday        True
2   OD1003 2024-06-04 18:45:00    Tuesday       False
3   OD1004 2024-06-07 09:30:45     Friday       False
4   OD1005 2024-06-08 20:10:00   Saturday        True
5   OD1006 2024-06-09 11:05:20     Sunday        True
6   OD1007 2024-06-12 16:40:10  Wednesday       False
7   OD1008 2024-06-15 13:15:00   Saturday        True

---

## 🎯 Key Takeaways & Best Practices
- **Format Specification**: Providing explicit format strings (e.g. `format='%Y-%m-%d %H:%M:%S'`) to `pd.to_datetime()` yields major performance speedups and eliminates ambiguous date parsing (e.g. Day-first vs Month-first).
- **Vectorized Accessor (`.dt`)**: Always leverage `.dt` for element-wise datetime attribute extraction (`.dt.year`, `.dt.month`, `.dt.day_name()`, `.dt.dayofweek`) rather than slower list comprehensions or lambda loops.
- **Frequency Resampling**: `df.resample()` functions like a temporal `groupby()`. Commonly used frequency aliases include `'D'` (daily), `'W'` (weekly), `'M'` / `'ME'` (month-end), and `'Q'` (quarterly).
- **Timezone Safety**: Distinguish between timezone-naive and timezone-aware timestamps. Use `.dt.tz_localize()` to attach a timezone to naive dates, and `.dt.tz_convert()` to shift between timezones.
- **Temporal Feature Engineering**: Features like `is_weekend`, `hour_of_day`, and `quarter` are critical predictive drivers for demand forecasting, sales estimation, and anomaly detection.