# SESSION 6 - Data Cleaning (Part 1: Missing Values)

**Curriculum Module:** Data Collection, Cleaning, Visualization and Analysis  
**Session:** 06 - Data Cleaning (Part 1: Missing Values)  
**Status:** ✅ Completed

---

## 📋 Topics Covered
1. **Identifying Missing Data**: Detecting missing values using `.isnull()`, `.isna()`, and `.notnull()`.
2. **Dropping Missing Data (`dropna`)**: Row/Column deletion with parameters (`axis`, `how='any'/'all'`, `thresh`).
3. **Statistical Imputation (`fillna`)**: Replacing null values with summary statistics (Mean, Median, Mode).
4. **Sequential Imputation**: Forward fill (`ffill`) and Backward fill (`bfill`) for ordered and sequential datasets.
5. **Missingness Mechanisms**: Conceptual evaluation of MCAR (Missing Completely at Random), MAR (Missing at Random), and MNAR (Missing Not at Random).

---

## Task 1: Ingest IPL Player Stats & Detect Missing Values

**Problem Statement:**  
*Download a sample CSV file of IPL player stats (include columns like player name, runs, matches, and some missing values). Load it into a pandas DataFrame and use `isnull()` and `notnull()` to print how many missing values are present in each column.*

In [1]:
import pandas as pd
import numpy as np

# Load IPL player stats dataset
df_ipl = pd.read_csv('ipl_player_stats.csv')
print('Dataset Preview:')
print(df_ipl.head(5))

# Method 1: Count missing values using .isnull().sum()
missing_isnull = df_ipl.isnull().sum()

# Method 2: Calculate missing values using .notnull()
# Total rows minus count of valid values gives missing count
missing_notnull = len(df_ipl) - df_ipl.notnull().sum()

print('\nMissing values count per column (using isnull):')
print(missing_isnull)

print('\nMissing values count per column (verified using notnull):')
print(missing_notnull)

Dataset Preview:
   player_id     player_name team  matches   runs  wickets  batting_avg  strike_rate
0          1     Virat Kohli  RCB       15  741.0      0.0        61.75       154.69
1          2    Rohit Sharma   MI       14  417.0      NaN        32.08       150.00
2          3  Jasprit Bumrah   MI       13    NaN     20.0          NaN          NaN
3          4    Sunil Narine  KKR       15  488.0     17.0        34.85       180.74
4          5        MS Dhoni  CSK       14  161.0      0.0        53.66       220.54

Missing values count per column (using isnull):
player_id      0
player_name    0
team           0
matches        0
runs           3
wickets        2
batting_avg    2
strike_rate    2

Missing values count per column (verified using notnull):
player_id      0
player_name    0
team           0
matches        0
runs           3
wickets        2
batting_avg    2
strike_rate    2

---

## Task 2: Remove Missing Rows with `dropna(axis=0, how='any')`

**Problem Statement:**  
*Using the loaded IPL player stats DataFrame, apply `dropna(axis=0, how='any')` to remove all rows with any missing data and display the shape of the DataFrame before and after dropping.*

In [2]:
# Inspect shape before dropping
shape_before = df_ipl.shape

# Apply dropna to remove any row containing at least one missing value
df_dropped = df_ipl.dropna(axis=0, how='any')
shape_after = df_dropped.shape

print(f'DataFrame Shape Before dropna: {shape_before}')
print(f'DataFrame Shape After dropna:  {shape_after}')
print(f'Rows removed due to missing values: {shape_before[0] - shape_after[0]}')

print('\nCleaned DataFrame (all complete rows):')
df_dropped

DataFrame Shape Before dropna: (10, 8)
DataFrame Shape After dropna:  (5, 8)
Rows removed due to missing values: 5

Cleaned DataFrame (all complete rows):
   player_id      player_name team  matches   runs  wickets  batting_avg  strike_rate
0          1      Virat Kohli  RCB       15  741.0      0.0        61.75       154.69
3          4     Sunil Narine  KKR       15  488.0     17.0        34.85       180.74
4          5         MS Dhoni  CSK       14  161.0      0.0        53.66       220.54
7          8  Ruturaj Gaikwad  CSK       14  583.0      0.0        53.00       141.16
8          9    Andre Russell  KKR       15  222.0     19.0        31.71       185.00

   player_id      player_name team  matches   runs  wickets  batting_avg  strike_rate
0          1      Virat Kohli  RCB       15  741.0      0.0        61.75       154.69
3          4     Sunil Narine  KKR       15  488.0     17.0        34.85       180.74
4          5         MS Dhoni  CSK       14  161.0      0.0        53.66       220.54
7          8  Ruturaj Gaikwad  CSK       14  583.0      0.0        53.00       141.16
8          9    Andre Russell  KKR       15  222.0     19.0        31.71       185.00

---

## Task 3: Mean Imputation on 'runs' Column with `fillna()`

**Problem Statement:**  
*For the 'runs' column in your IPL player stats DataFrame, use `fillna()` to replace missing values with the mean of the column. Print the updated column to verify the changes.*

In [3]:
# Compute the mean of the 'runs' column (excluding nulls)
runs_mean = df_ipl['runs'].mean()
print(f'Calculated Mean Runs: {runs_mean:.2f}')

# Compare original vs imputed runs column
df_ipl_imputed = df_ipl.copy()
df_ipl_imputed['runs'] = df_ipl_imputed['runs'].fillna(runs_mean)

# Display player name with original and updated runs to verify imputation
verification_df = pd.DataFrame({
    'player_name': df_ipl['player_name'],
    'runs_original': df_ipl['runs'],
    'runs_imputed': df_ipl_imputed['runs'].round(2)
})

print('\nVerification Table (Missing runs imputed with mean):')
print(verification_df)

print(f'\nMissing values in updated runs column: {df_ipl_imputed["runs"].isnull().sum()}')

Calculated Mean Runs: 441.57

Verification Table (Missing runs imputed with mean):
        player_name  runs_original  runs_imputed
0       Virat Kohli          741.0        741.00
1      Rohit Sharma          417.0        417.00
2    Jasprit Bumrah            NaN        441.57
3      Sunil Narine          488.0        488.00
4          MS Dhoni          161.0        161.00
5  Heinrich Klaasen          479.0        479.00
6       Pat Cummins            NaN        441.57
7   Ruturaj Gaikwad          583.0        583.00
8     Andre Russell          222.0        222.00
9     Kuldeep Yadav            NaN        441.57

Missing values in updated runs column: 0

        player_name  runs_original  runs_imputed
0       Virat Kohli          741.0        741.00
1      Rohit Sharma          417.0        417.00
2    Jasprit Bumrah            NaN        441.57
3      Sunil Narine          488.0        488.00
4          MS Dhoni          161.0        161.00
5  Heinrich Klaasen          479.0        479.00
6       Pat Cummins            NaN        441.57
7   Ruturaj Gaikwad          583.0        583.00
8     Andre Russell          222.0        222.00
9     Kuldeep Yadav            NaN        441.57

---

## Task 4: Sequential Fill (Forward Fill + Backward Fill)

**Problem Statement:**  
*Simulate a Zomato-style restaurant ratings dataset with some missing ratings. Use forward fill (`method='ffill'` or `.ffill()`) to fill missing values in the ratings column, then use backward fill (`method='bfill'` or `.bfill()`) for any remaining missing values. Show the before and after results.*

In [4]:
# Load simulated Zomato restaurant ratings dataset
df_zomato = pd.read_csv('zomato_ratings.csv')

# Create copy for sequential imputation
df_ratings = df_zomato.copy()

# Step 1: Forward fill propagates the last valid rating forward
df_ratings['rating_ffill'] = df_ratings['rating'].ffill()

# Step 2: Backward fill handles leading NaNs that ffill cannot reach
df_ratings['rating_final'] = df_ratings['rating_ffill'].bfill()

print('Comparison Table: Before vs After Sequential Imputation:')
comparison = df_ratings[['restaurant_name', 'rating', 'rating_ffill', 'rating_final']]
comparison

Comparison Table: Before vs After Sequential Imputation:
     restaurant_name  rating  ffill_rating  final_rating
0      The Fatty Bao     NaN           NaN           4.5
1           Truffles     4.5           4.5           4.5
2       Corner House     NaN           4.5           4.5
3      Meghana Foods     NaN           4.5           4.5
4               Toit     4.7           4.7           4.7
5   Vidyarthi Bhavan     4.4           4.4           4.4
6   Glen's Bakehouse     NaN           4.4           4.4
7  Empire Restaurant     3.9           3.9           3.9

     restaurant_name  rating  ffill_rating  final_rating
0      The Fatty Bao     NaN           NaN           4.5
1           Truffles     4.5           4.5           4.5
2       Corner House     NaN           4.5           4.5
3      Meghana Foods     NaN           4.5           4.5
4               Toit     4.7           4.7           4.7
5   Vidyarthi Bhavan     4.4           4.4           4.4
6   Glen's Bakehouse     NaN           4.4           4.4
7  Empire Restaurant     3.9           3.9           3.9

---

## Task 5: Missingness Mechanism Analysis (MCAR, MAR, MNAR)

**Problem Statement:**  
*Pick any one column with missing values from your dataset and explain which missingness mechanism (MCAR, MAR, or MNAR) is most likely and why, using 2-3 sentences.*  
*Hint: Think about whether the missing data is random or related to other factors in the dataset.*

### 🔬 Missingness Mechanism Evaluation

#### **Selected Column:** `wickets` (from `ipl_player_stats.csv`)

> **Most Likely Mechanism:** **MAR (Missing at Random)**
> 
> **Explanation:**  
> In the IPL dataset, missing values in the `wickets` column are not occurring completely at random; rather, they are systematically related to the player's primary role in the team. Specialist batsmen and wicketkeepers (such as Virat Kohli, Heinrich Klaasen, or MS Dhoni) rarely or never bowl in a match, meaning their bowling stats are unrecorded or absent conditioned directly on their observed batting specialty. Because the probability of missingness can be fully explained by another observed variable (`player role` / `runs`), it represents **Missing at Random (MAR)**.

---

#### *Alternative Perspective on Zomato `rating` Column:*
> In restaurant review datasets, missing ratings often exemplify **MNAR (Missing Not at Random)**. Diners with neutral or average experiences are significantly less inclined to leave any rating on the app compared to customers with exceptionally positive or negative experiences. Thus, the missingness depends directly on the unobserved customer sentiment itself.

---

## 🎯 Key Takeaways & Best Practices
- **Detection**: Always begin EDA with `df.isnull().sum()` or visual heatmaps to assess missingness proportion per feature.
- **Deletion vs. Imputation**:
  - `dropna(how='any')` can cause drastic data loss (here reducing rows from 10 to 5, a 50% drop!). Use it only when missing values are scarce (< 2-3%).
  - Imputation preserves sample size. Use **Mean** for symmetric distributions, **Median** for skewed data/outliers, and **Mode** for categorical data.
- **Sequential Imputation**: For time-series, order logs, or sequential records, pairing `ffill()` followed by `bfill()` ensures all gaps (including leading missing values) are filled.
- **Understanding Mechanisms**: Recognizing whether data is **MCAR**, **MAR**, or **MNAR** prevents introducing bias into downstream machine learning models.